default: detect_4000.heavy
detect_1.heavy:
	heavyml_train -gdr 1 -gda 100 -n "#features->[[1000*[all]],[#labels*[all],4*[all]]]" -fnt 4 -o detect_1.heavy train/

detect_100.heavy: detect_1.heavy
	heavyml_train -gdr 99 -gda 0 -d -m detect_1.heavy -fnt 4 -o detect_100.heavy train/

detect_200.heavy: detect_100.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_100.heavy -fnt 4 -o detect_200.heavy train/

detect_300.heavy: detect_200.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_200.heavy -fnt 4 -o detect_300.heavy train/

detect_400.heavy: detect_300.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_300.heavy -fnt 4 -o detect_400.heavy train/

detect_500.heavy: detect_400.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_400.heavy -fnt 4 -o detect_500.heavy train/

detect_600.heavy: detect_500.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_500.heavy -fnt 4 -o detect_600.heavy train/

detect_700.heavy: detect_600.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_600.heavy -fnt 4 -o detect_700.heavy train/

detect_800.heavy: detect_700.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_700.heavy -fnt 4 -o detect_800.heavy train/

detect_900.heavy: detect_800.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_800.heavy -fnt 4 -o detect_900.heavy train/

detect_1000.heavy: detect_900.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_900.heavy -fnt 4 -o detect_1000.heavy train/

detect_1100.heavy: detect_1000.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_1000.heavy -fnt 4 -o detect_1100.heavy train/

detect_1200.heavy: detect_1100.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_1100.heavy -fnt 4 -o detect_1200.heavy train/

detect_1300.heavy: detect_1200.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_1200.heavy -fnt 4 -o detect_1300.heavy train/

detect_1400.heavy: detect_1300.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_1300.heavy -fnt 4 -o detect_1400.heavy train/

detect_1500.heavy: detect_1400.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_1400.heavy -fnt 4 -o detect_1500.heavy train/

detect_1600.heavy: detect_1500.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_1500.heavy -fnt 4 -o detect_1600.heavy train/

detect_1700.heavy: detect_1600.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_1600.heavy -fnt 4 -o detect_1700.heavy train/

detect_1800.heavy: detect_1700.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_1700.heavy -fnt 4 -o detect_1800.heavy train/

detect_1900.heavy: detect_1800.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_1800.heavy -fnt 4 -o detect_1900.heavy train/

detect_2000.heavy: detect_1900.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_1900.heavy -fnt 4 -o detect_2000.heavy train/

detect_2100.heavy: detect_2000.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_2000.heavy -fnt 4 -o detect_2100.heavy train/

detect_2200.heavy: detect_2100.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_2100.heavy -fnt 4 -o detect_2200.heavy train/

detect_2300.heavy: detect_2200.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_2200.heavy -fnt 4 -o detect_2300.heavy train/

detect_2400.heavy: detect_2300.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_2300.heavy -fnt 4 -o detect_2400.heavy train/

detect_2500.heavy: detect_2400.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_2400.heavy -fnt 4 -o detect_2500.heavy train/

detect_2600.heavy: detect_2500.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_2500.heavy -fnt 4 -o detect_2600.heavy train/

detect_2700.heavy: detect_2600.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_2600.heavy -fnt 4 -o detect_2700.heavy train/

detect_2800.heavy: detect_2700.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_2700.heavy -fnt 4 -o detect_2800.heavy train/

detect_2900.heavy: detect_2800.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_2800.heavy -fnt 4 -o detect_2900.heavy train/

detect_3000.heavy: detect_2900.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_2900.heavy -fnt 4 -o detect_3000.heavy train/

detect_3100.heavy: detect_3000.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_3000.heavy -fnt 4 -o detect_3100.heavy train/

detect_3200.heavy: detect_3100.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_3100.heavy -fnt 4 -o detect_3200.heavy train/

detect_3300.heavy: detect_3200.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_3200.heavy -fnt 4 -o detect_3300.heavy train/

detect_3400.heavy: detect_3300.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_3300.heavy -fnt 4 -o detect_3400.heavy train/

detect_3500.heavy: detect_3400.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_3400.heavy -fnt 4 -o detect_3500.heavy train/

detect_3600.heavy: detect_3500.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_3500.heavy -fnt 4 -o detect_3600.heavy train/

detect_3700.heavy: detect_3600.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_3600.heavy -fnt 4 -o detect_3700.heavy train/

detect_3800.heavy: detect_3700.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_3700.heavy -fnt 4 -o detect_3800.heavy train/

detect_3900.heavy: detect_3800.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_3800.heavy -fnt 4 -o detect_3900.heavy train/

detect_4000.heavy: detect_3900.heavy
	heavyml_train -gdr 100 -gda 0 -d -m detect_3900.heavy -fnt 4 -o detect_4000.heavy train/
